FROM node:18-alpine as builder
WORKDIR /builder
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build

FROM node:18-alpine as runner
WORKDIR /app
RUN apk update \
    && apk add jq \
    && rm -rf /var/cache/apk/*
ENV NODE_ENV production
COPY package.json yarn.lock ./
RUN yarn --prod
COPY --from=builder /builder/build/ ./build


EXPOSE 3001
CMD [ "yarn", "prod" ]